add_test([=[Image.TestP6]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Image.TestP6]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Image.TestP6]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Image.TestBMP]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Image.TestBMP]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Image.TestBMP]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Image.TestPNG]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Image.TestPNG]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Image.TestPNG]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Operations.Greyscale]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Operations.Greyscale]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Operations.Greyscale]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Operations.BrightnessAndContrast]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Operations.BrightnessAndContrast]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Operations.BrightnessAndContrast]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Filters.Gaussian]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Filters.Gaussian]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Filters.Gaussian]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Filters.Edge]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Filters.Edge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Filters.Edge]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Filters.Custom]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Filters.Custom]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Filters.Custom]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Filters.EdgeLarge]=]  /home/runner/work/imaging/imaging/_codeql_build_dir/tests/unit_tests [==[--gtest_filter=Filters.EdgeLarge]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Filters.EdgeLarge]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/imaging/imaging/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  unit_tests_TESTS Image.TestP6 Image.TestBMP Image.TestPNG Operations.Greyscale Operations.BrightnessAndContrast Filters.Gaussian Filters.Edge Filters.Custom Filters.EdgeLarge)
